workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.example.pmvjrc
    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Build iOS
        script: flutter build ios

      - name: Archive and export IPA
        script: |
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive archive

          xcodebuild \
            -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/ipa
    artifacts:
      - build/ipa/*.ipa
